--
INSERT INTO FT_T_DSRC (DATA_SRC_ID, START_TMS, LAST_CHG_TMS, LAST_CHG_USR_ID, DATA_SRC_NME) SELECT 'MANUAL',SYSDATE,SYSDATE,'ICR:CSTM','Manual'  FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM FT_T_DSRC WHERE DATA_SRC_ID = 'MANUAL');
